# Generated by Django 6.0.1 on 2026-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='Pełna nazwa oddziału lub ośrodka medycznego', max_length=500, verbose_name='Nazwa oddziału/ośrodka')),
                ('treatedDiseases', models.TextField(help_text='Lista chorób oddzielona przecinkami', verbose_name='Leczone choroby')),
                ('address', models.TextField(help_text='Pełny adres ośrodka', verbose_name='Adres')),
                ('phone', models.TextField(help_text='Numery telefonów kontaktowych', verbose_name='Telefon')),
                ('lat', models.FloatField(help_text='Latitude', verbose_name='Szerokość geograficzna')),
                ('lng', models.FloatField(help_text='Longitude', verbose_name='Długość geograficzna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ośrodek Medyczny',
                'verbose_name_plural': 'Ośrodki Medyczne',
                'ordering': ['department'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='map_medical_lat_ecf4be_idx'), models.Index(fields=['department'], name='map_medical_departm_fce6ac_idx')],
            },
        ),
    ]
