# Generated by Django 6.0.1 on 2026-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Banner image (recommended height: ~300px, full width)', upload_to='banners/')),
                ('link', models.URLField(help_text='Destination URL when banner is clicked', max_length=500)),
                ('position', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('content_top', 'Content Top'), ('content_bottom', 'Content Bottom')], db_index=True, help_text='Display location on the website', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this banner is currently active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banery',
                'ordering': ['position', 'order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active', 'order'], name='banners_ban_positio_6899c1_idx')],
            },
        ),
    ]
