# Generated by Django 6.0.1 on 2026-01-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('content_top', 'Content Top'), ('content_bottom', 'Content Bottom'), ('home_banner_1', 'Home Banner 1 (after 3 posts)'), ('home_banner_2', 'Home Banner 2 (after 6 posts)'), ('home_banner_3', 'Home Banner 3 (after 12 posts)')], db_index=True, help_text='Display location on the website', max_length=50),
        ),
    ]
