# Generated by Django 6.0.1 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('home_banner_1', 'Home Banner 1 (after 3 posts)'), ('home_banner_2', 'Home Banner 2 (after 6 posts)'), ('home_banner_3', 'Home Banner 3 (after 12 posts)')], db_index=True, help_text='Display location on the website', max_length=50),
        ),
    ]
