# Generated by Django 6.0.1 on 2026-01-29 19:01

import apps.posts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.posts.models.gallery_image_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Opcjonalny podpis zdjęcia', max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='posts.post')),
            ],
            options={
                'verbose_name': 'Zdjęcie galerii',
                'verbose_name_plural': 'Zdjęcia galerii',
                'ordering': ['position', 'uploaded_at'],
                'indexes': [models.Index(fields=['post', 'position'], name='posts_galle_post_id_641153_idx')],
            },
        ),
    ]
