# Generated by Django 6.0.1 on 2026-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_image',
        ),
        migrations.DeleteModel(
            name='RelatedPost',
        ),
    ]
