# Generated by Django 6.0.1 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_thumbnail_image_delete_relatedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (max 160 characters). If empty, excerpt will be used.', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma-separated (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom Open Graph image. If empty, hero_image will be used.', null=True, upload_to='posts/og_images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional image caption', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='Preview description for listing display', max_length=500),
        ),
    ]
